@baseurl = http://localhost:3001/api

###

GET http://localhost:3001/api/hotel
Content-Type: application/json

###
GET http://localhost:3001/api/hotel?rating=5
Content-Type: application/json

###
###
GET http://localhost:3001/api/hotel?category=1
Content-Type: application/json
###
POST  http://localhost:3001/api/hotel/623a1cbf22edec7db199b987/comment?category=1
Content-Type: application/json

{
	"rating": 3,
	"comment": "desde rest client vscod",
	"user": ""
}
###